name: Canary

on:
  push:
  workflow_dispatch:
  schedule:
    # Run every day
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ts
        run: sudo apt install moreutils

      - name: Install opam & packages
        run: bash ./install_linux.sh
